/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from.sistema;

import banco.Conexao;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class Pedidos extends javax.swing.JFrame {

    Double valoTotal = 0.0;

    /**
     * Creates new form CadPedidos
     */
    public Pedidos() {
        initComponents();
        comboboxTipo.buscaResult("SELECT id_tipoProduto, tipo FROM tipoProduto ORDER BY tipo ASC");
        comboboxMesa.buscaResult("SELECT id_mesas, numero FROM mesas ORDER BY numero ASC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboboxTipo = new util.Combobox();
        jLabel3 = new javax.swing.JLabel();
        comboboxProduto = new util.Combobox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValUnit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboboxMesa = new util.Combobox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInfoPedido = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCompl_Adicionais = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTotalPedido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemov = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Pedidos");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 146, 156));
        jTextField1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle de Pedidos");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");

        comboboxTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboboxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxTipoItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Produto:");

        comboboxProduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboboxProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxProdutoItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Val Unitário:");

        jTextFieldValUnit.setEditable(false);
        jTextFieldValUnit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Quantidade:");

        jTextFieldQtd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Mesa:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 146, 156)), "Informações/Pedido", 0, 2, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jTableInfoPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Tipo", "Id Prod.", "Produto", "Quantidade", "Val Unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableInfoPedido);
        if (jTableInfoPedido.getColumnModel().getColumnCount() > 0) {
            jTableInfoPedido.getColumnModel().getColumn(0).setResizable(false);
        }

        jTextAreaCompl_Adicionais.setColumns(10);
        jTextAreaCompl_Adicionais.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCompl_Adicionais);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Complementos/Adicionais");

        jTextFieldTotalPedido.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextFieldTotalPedido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Total Pedido:");

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Limpar.png"))); // NOI18N
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButtonLimpar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/adicionar.png"))); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonRemov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/excluir-16.png"))); // NOI18N
        jButtonRemov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 146, 156));
        jTextField4.setBorder(null);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pedido.png"))); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SALVAR / ENVIAR AO CAIXA");

        jComboBoxStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberto", "Fechado" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField4)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemov))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jButtonSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboboxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldValUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(comboboxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAdd)
                        .addComponent(jButtonRemov)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxTipoItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            comboboxProduto.buscaResult("SELECT id_produtos, nome FROM produtos WHERE id_tipoProduto = " + comboboxTipo.getValor());

        }

    }//GEN-LAST:event_comboboxTipoItemStateChanged

    private void comboboxProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxProdutoItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jTextFieldValUnit.setText("");
            try {
                PreparedStatement ps = null;
                Connection con = Conexao.getInstancia();
                String sql = "SELECT * FROM produtos where id_produtos = " + comboboxProduto.getValor();
                ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                int cont = 0;

                rs.next();

                jTextFieldValUnit.setText(rs.getString(4));
                ps.close();
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_comboboxProdutoItemStateChanged

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        if (comboboxTipo.getSelectedItem().equals("Selecione")) {
            comboboxTipo.requestFocus();
            JOptionPane.showMessageDialog(this, "Selecione um tipo para o pedido");
            return;
        } else if (comboboxProduto.getSelectedItem().equals("Selecione")) {
            comboboxProduto.requestFocus();
            JOptionPane.showMessageDialog(this, "Selecione um pedido");
            return;
        } else if (jTextFieldQtd.getText().equals("")) {
            jTextFieldQtd.requestFocus();
            JOptionPane.showMessageDialog(this, "Informe a quantidade");
            return;
        } else if (comboboxMesa.getSelectedItem().equals("Selecione")) {
            comboboxMesa.requestFocus();
            JOptionPane.showMessageDialog(null, "Selecione uma mesa");
            return;
        }

        String[] linha = {
            String.valueOf(comboboxMesa.getSelectedItem()),
            String.valueOf(comboboxTipo.getSelectedItem()),
            String.valueOf(comboboxProduto.getSelectedIndex()),
            String.valueOf(comboboxProduto.getSelectedItem()),
            String.valueOf(jTextFieldQtd.getText()),
            String.valueOf(jTextFieldValUnit.getText()),};

        DefaultTableModel modelo = (DefaultTableModel) jTableInfoPedido.getModel();
        modelo.addRow(linha);

        valoTotal = valoTotal + (Double.parseDouble(jTextFieldQtd.getText()))
                * (Double.parseDouble(jTextFieldValUnit.getText()));

        jTextFieldTotalPedido.setText(formataValor(valoTotal));
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovActionPerformed

        int linhaSelecionada = jTableInfoPedido.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um pedido");
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int opcao = JOptionPane.showConfirmDialog(null, "Confirmar exclusão?", "Exclusão", dialogButton);

            if (opcao == JOptionPane.YES_OPTION) {
                try {
                    valoTotal = valoTotal - (Double.parseDouble(jTableInfoPedido.getModel().
                            getValueAt(linhaSelecionada, 4).toString())
                            * (Double.parseDouble(jTableInfoPedido.getModel().getValueAt(linhaSelecionada, 5).toString())));

                    jTextFieldTotalPedido.setText(formataValor(valoTotal));

                    DefaultTableModel modelo = (DefaultTableModel) jTableInfoPedido.getModel();
                    modelo.removeRow(linhaSelecionada);
                    limparTela();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro não esperado: " + ex.getMessage());
                }
            }
        }

    }//GEN-LAST:event_jButtonRemovActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        try {
            if (comboboxTipo.eVazio()) {
                JOptionPane.showMessageDialog(null, "Escolha o tipo");
                return;
            }
            if (comboboxProduto.eVazio()) {
                JOptionPane.showMessageDialog(null, "Informe o produto");
                return;
            }
            if (comboboxMesa.eVazio()) {
                JOptionPane.showMessageDialog(null, "Informe a mesa");
                return;
            } else {
                Timestamp datapedido = new Timestamp(new Date().getTime());

                for (int linha = 0; linha < jTableInfoPedido.getRowCount(); linha++) {
                    String sql = "INSERT INTO pedidos ("
                            + "datapedido, "
                            + "qtd, "
                            + "valUnit, "
                            + "status, "
                            + "id_mesas, "
                            + "id_produtos) "
                            + "VALUES (?, ?, ?, ?, ?, ?)";

                    Connection con = Conexao.getInstancia();
                    PreparedStatement ps = con.prepareStatement(sql);

                    DefaultTableModel tabela = (DefaultTableModel) jTableInfoPedido.getModel();

                    ps.setTimestamp(1, datapedido);
                    ps.setInt(2, Integer.parseInt(tabela.getValueAt(linha, 4).toString()));
                    ps.setDouble(3, Double.parseDouble(tabela.getValueAt(linha, 5).toString()));

                    Boolean status = Boolean.parseBoolean(jComboBoxStatus.getSelectedItem().toString());

                    if (jComboBoxStatus.getSelectedIndex() == 0) {
                        ps.setBoolean(4, false);
                    } else {
                        ps.setBoolean(4, true);
                    }

                    ps.setInt(5, Integer.parseInt(tabela.getValueAt(linha, 0).toString()));
                    ps.setInt(6, Integer.parseInt(tabela.getValueAt(linha, 2).toString()));

                    ps.executeUpdate();
                    ps.close();
                }
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro não esperado: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed

        if (!jTextAreaCompl_Adicionais.getText().equals("")) {
            jTextAreaCompl_Adicionais.setText("");
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.Combobox comboboxMesa;
    private util.Combobox comboboxProduto;
    private util.Combobox comboboxTipo;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonRemov;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableInfoPedido;
    private javax.swing.JTextArea jTextAreaCompl_Adicionais;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JTextField jTextFieldTotalPedido;
    private javax.swing.JTextField jTextFieldValUnit;
    // End of variables declaration//GEN-END:variables

    private String formataValor(Double valor) {
        return String.format("%.2f", valor).replaceAll(",", ".");
    }

    private void limparTela() {
        comboboxTipo.limpar();
        comboboxProduto.limpar();
        comboboxMesa.limpar();
        jTextFieldQtd.setText("");
    }

}
