/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from.sistema;

import banco.Conexao;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import util.A;

/**
 *
 * @author Edmilson
 */
public final class Recebimento extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Principal
     */
    List<JButton> botoesGrupo = new ArrayList<>();
    List<Integer> idsMesa = new ArrayList<>();
    Double valorTotalCaixa = 0.0;
    Double valorRecebidoCaixa = 0.0;
    Boolean op = null;

    public Recebimento() {
        initComponents();
        montagrupo();
        Desabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();
        jPanelPedidosAtivos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTotalVenda = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButtonFinalizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDataAbertura = new javax.swing.JTextField();
        jTextFieldDataFechamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValReceb = new javax.swing.JTextField();
        jButtonAbrirC = new javax.swing.JButton();
        jButtonFecharC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recebimento");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 146, 156));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("CAIXA -/- RECEBIMENTO");
        jTextField3.setBorder(null);

        jTableDados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod/Pedido", "Cod/Mesa", "Produto", "Quantidade", "Valor Unitário", "Total/Parcial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(jTableDados);

        jPanelPedidosAtivos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pedidos Ativos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 12), new java.awt.Color(0, 146, 156))); // NOI18N
        jPanelPedidosAtivos.setLayout(new java.awt.GridLayout(5, 5));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("TOTAL:");

        jTextFieldTotalVenda.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTextFieldTotalVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonCancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");

        jTextField2.setBackground(new java.awt.Color(0, 146, 156));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Desenvolvido por: Edmilson Barreto");
        jTextField2.setBorder(null);
        jTextField2.setCaretPosition(23);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField2.setPreferredSize(new java.awt.Dimension(155, 15));

        jButtonFinalizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/confirmar.png"))); // NOI18N
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 146, 156)), "CAIXA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("DataHora/Abertura:");

        jTextFieldDataAbertura.setEditable(false);
        jTextFieldDataAbertura.setBackground(new java.awt.Color(0, 146, 156));
        jTextFieldDataAbertura.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldDataAbertura.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDataAbertura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldDataFechamento.setEditable(false);
        jTextFieldDataFechamento.setBackground(new java.awt.Color(0, 146, 156));
        jTextFieldDataFechamento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldDataFechamento.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDataFechamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("DataHora/Fechamento:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("STATUS:");

        jTextFieldStatus.setEditable(false);
        jTextFieldStatus.setBackground(new java.awt.Color(0, 146, 156));
        jTextFieldStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldStatus.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldStatus.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Valor/Recebimento");

        jTextFieldValReceb.setEditable(false);
        jTextFieldValReceb.setBackground(new java.awt.Color(0, 146, 156));
        jTextFieldValReceb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldValReceb.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldValReceb.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonAbrirC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonAbrirC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/abrirC.png"))); // NOI18N
        jButtonAbrirC.setText("Abrir");
        jButtonAbrirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirCActionPerformed(evt);
            }
        });

        jButtonFecharC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonFecharC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fecharC.png"))); // NOI18N
        jButtonFecharC.setText("Fechar");
        jButtonFecharC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Valor/Total");

        jTextFieldValorTotal.setBackground(new java.awt.Color(0, 146, 156));
        jTextFieldValorTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldValorTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldValorTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("?");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFecharC, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbrirC, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValReceb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldDataAbertura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addComponent(jTextFieldDataFechamento, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldValReceb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrirC)
                    .addComponent(jButtonFecharC))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3)
            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanelPedidosAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFinalizar))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonFinalizar)
                                    .addComponent(jButtonCancelar)))
                            .addComponent(jPanelPedidosAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed

        int st = 0;

        try {
            for (int linha = 0; linha < jTableDados.getRowCount(); linha++) {
                String sql = "INSERT INTO recebimento ("
                        + "codigoPedido, "
                        + "produtos, "
                        + "quantidade, "
                        + "valorUnitario, "
                        + "totalParcial, "
                        + "id_mesas) "
                        + "VALUES (?, ?, ?, ?, ?, ?)";

                Connection con = Conexao.getInstancia();
                PreparedStatement ps = con.prepareStatement(sql);

                DefaultTableModel tabela = (DefaultTableModel) jTableDados.getModel();

                ps.setInt(1, Integer.parseInt(tabela.getValueAt(linha, 0).toString()));
                ps.setString(2, tabela.getValueAt(linha, 2).toString());
                ps.setInt(3, Integer.parseInt(tabela.getValueAt(linha, 3).toString()));
                ps.setDouble(4, Double.parseDouble(tabela.getValueAt(linha, 4).toString()));
                ps.setDouble(5, Double.parseDouble(tabela.getValueAt(linha, 5).toString()));
                ps.setInt(6, Integer.parseInt(tabela.getValueAt(linha, 1).toString()));

                ps.executeUpdate();
                st++;
                ps.close();
            }
            if (st == 0) {
                JOptionPane.showMessageDialog(null, "Escolha um pedido");
            } else {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
            }

            valorRecebidoCaixa = Double.parseDouble(jTextFieldTotalVenda.getText());
            valorTotalCaixa = valorTotalCaixa + Double.parseDouble(jTextFieldTotalVenda.getText());

            LimparTable();
            jTextFieldTotalVenda.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro não esperado: " + e.getMessage());
        }

    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonAbrirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirCActionPerformed

        Timestamp dataAbertura = new Timestamp(new Date().getTime());
        //SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");

        jTextFieldDataAbertura.setText(dataAbertura.toString());

        jTextFieldStatus.setText("-- Aberto --");

        jTextFieldDataFechamento.setText("");
        jTextFieldValReceb.setText("");
        jTextFieldValorTotal.setText("");

        Habilitar();

    }//GEN-LAST:event_jButtonAbrirCActionPerformed

    private void jButtonFecharCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCActionPerformed

        Timestamp dataFechamento = new Timestamp(new Date().getTime());

        jTextFieldStatus.setText("-- Fechado --");

        //SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
        jTextFieldDataFechamento.setText(dataFechamento.toString());

        jTextFieldValReceb.setText(A.formataValor(valorRecebidoCaixa));
        jTextFieldValorTotal.setText(A.formataValor(valorTotalCaixa));

        try {
            String sql = "INSERT INTO caixa ("
                    + "dataAbertura, "
                    + "dataFechamento, "
                    + "valor_receb, "
                    + "valor_total)"
                    + "VALUES (?, ?, ?, ?)";

            Connection con = Conexao.getInstancia();
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setTimestamp(1, Timestamp.valueOf(jTextFieldDataAbertura.getText()));
            ps.setTimestamp(2, Timestamp.valueOf(jTextFieldDataFechamento.getText()));
            ps.setDouble(3, Double.parseDouble(jTextFieldValReceb.getText()));
            ps.setDouble(4, Double.parseDouble(jTextFieldValorTotal.getText()));

            ps.executeUpdate();
            ps.close();

            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro não esperado: " + e.getMessage());
        }

        Desabilitar();
        LimparTable();

    }//GEN-LAST:event_jButtonFecharCActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        JOptionPane.showMessageDialog(null, "Referência do ultimo valor recebido no dia");

    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recebimento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recebimento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recebimento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recebimento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recebimento().setVisible(true);
            }
        });
    }

    /*
    Date data = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    jTextFieldDataAbertura.setText(formatador.format(data));
     */
    public void Habilitar() {

        op = true;
        jTableDados.setVisible(true);
        jTextFieldTotalVenda.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonFinalizar.setEnabled(true);
        jButtonFecharC.setEnabled(true);

    }

    public void Desabilitar() {

        op = false;
        jTableDados.setVisible(false);
        jTextFieldTotalVenda.setText("");
        jTextFieldTotalVenda.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonFinalizar.setEnabled(false);
        jButtonFecharC.setEnabled(false);

    }

    public void LimparTable() {

        DefaultTableModel modelo = (DefaultTableModel) jTableDados.getModel();
        for (int i = 0; i <= modelo.getRowCount(); i++) {
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirC;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFecharC;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanelPedidosAtivos;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableDados;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldDataAbertura;
    private javax.swing.JTextField jTextFieldDataFechamento;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTotalVenda;
    private javax.swing.JTextField jTextFieldValReceb;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables

    void montagrupo() {

        String sql = "SELECT m.id_mesas, m.numero FROM pedidos p, mesas m WHERE m.id_mesas = p.id_mesas AND p.status = 0 GROUP BY m.numero";

        Connection con;
        try {
            JPanel painelMesa = new JPanel();
            con = Conexao.getInstancia();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                int tamanho = rs.getFetchSize();
                painelMesa.setLayout(new GridLayout(tamanho, 5, 1, 1));
                painelMesa.setEnabled(false);
                try {
                    rs.beforeFirst();
                    int x = 0;
                    while (rs.next()) {
                        //  System.out.println("ererer" + rs.getString("nomesubgrupo"));
                        JButton jbutton = new JButton(rs.getString("numero"));
                        jbutton.setSize(100, 30);
                        jbutton.setActionCommand(String.valueOf(x));
                        jbutton.addActionListener(this);
                        //codgrupos.add(rs.getInt("id_mesas"));
                        botoesGrupo.add(jbutton);
                        idsMesa.add(rs.getInt("id_mesas"));
                        x++;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                for (JButton j : botoesGrupo) {
                    painelMesa.add(j);
                }
            } else {
                jPanelPedidosAtivos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)
                ), "Mesa Vazia", 0, 2, new java.awt.Font("Serif", 1, 12),
                        new java.awt.Color(0, 146, 156))); // NOI18N
            }
            jPanelPedidosAtivos.add(new JScrollPane(painelMesa), BorderLayout.CENTER);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Integer idMesa = idsMesa.get(Integer.parseInt(e.getActionCommand()));
        try {
            DefaultTableModel modelo = (DefaultTableModel) jTableDados.getModel();
            modelo.setNumRows(0);

            String sql = "SELECT p.*, pr.nome FROM pedidos p, produtos pr "
                    + "WHERE p.id_produtos = pr.id_produtos AND p.id_mesas = ?"
                    + " AND status = false";

            Connection con = Conexao.getInstancia();
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setInt(1, idMesa);

            ResultSet rs = ps.executeQuery();

            Double total = 0.0;
            if (op) {
                while (rs.next()) {
                    String[] novaLinha = {
                        String.valueOf(rs.getInt("id_pedidos")),
                        String.valueOf(rs.getInt("id_mesas")),
                        rs.getString("nome"),
                        String.valueOf(rs.getInt("qtd")),
                        A.formataValor(rs.getDouble("valUnit")),
                        String.valueOf(A.formataValor(rs.getInt("qtd") * rs.getDouble("valUnit")))
                    };
                    modelo.addRow(novaLinha);
                    total = total + rs.getInt("qtd") * rs.getDouble("valUnit");
                }
                jTextFieldTotalVenda.setText(A.formataValor(total));

                rs.close();
                ps.close();
            } else if (op == false) {
                rs.close();
                ps.close();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro não esperado: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
}
/*
    private void carregaCombo() {

        //Pesquisa no BD.
        try {
            PreparedStatement ps = null;
            Connection con = Conexao.getInstancia();
            String sql = "SELECT id_cliente,nome_cliente FROM cliente";
            ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            int cont = 0;
            idsCliente.add(0);
            jcCliente.addItem("Selecione um Cliente");
            while (rs.next()) {
                //carrega o array dos codigos
                idsCliente.add(rs.getInt(1));
                //carrega os nomes pro combo
                jcCliente.addItem(rs.getString(2));

            }

            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro não encontrado: " + e.getMessage());
        }
    }
 */
